# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Panorama_DG_Template
# label used for menu selection
label: 1Panorama_DG_Template
description: Device Group and Template Configuration

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panorama
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Panorama_Workflow

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: some_template
    description: Template Name
    default: MyTemplate
    type_hint: text
  - name: some_devicegroup
    description: DeviceGroup Name
    default: MyDeviceGroup
    type_hint: text
  
# ---------------------------------------------------------------------
# end of variables section

snippets:
  - name: DG_Template
    file: DG_Template.xml